# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Release to Maven Central
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
        check-latest: true
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME # env variable for username in deploy
        server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
        settings-path: ${{ github.workspace }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: >
        mvn
        --batch-mode
        --activate-profiles release
        --file pom.xml
        --settings $GITHUB_WORKSPACE/settings.xml
        clean
        verify
      env:
        SIGN_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        SIGN_KEY_PASS: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    - name: Publish to Maven Central
      run: >
        mvn
        --batch-mode
        --activate-profiles release
        --file pom.xml
        --settings $GITHUB_WORKSPACE/settings.xml
        deploy
        -Dmaven.install.skip=true
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
    - name: Create an automatic release
      uses: marvinpinto/action-automatic-releases@v1.1.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          - LICENSE.txt
          - README.md
          - *.jar
          - *.jar.asc
